### ISSUE TITLE
Is this project still living?

### ISSUE THREAD

**Issue by christopherdumas** [shymega/guile-rs#5]
This project looks really interesting and would be a big help to my current project (https://github.com/christopherdumas/Skyspace) if it works well enough. Can I still use this with Rust 1.0? Also, is there any documentation at all? I'm okay with reading the source if I have to.

**Comment by shymega** [comment]
Yeah, I wanted to use this project to configure my text editor - Xt - in, but I'm not convinced it's maintained.. so I _was_ going to fork it, but then I wasn't sure what to do, so it's on the backburner now. Shame really :/

**Comment by lidavidm** [comment]
Ah I'm very sorry. No, it's not. If any of you would like to take it over, I can see about handing you the name on Cargo as well as this repository. @christopherdumas @shymega

**Comment by shymega** [comment]
@lidavidm I'd be more than happy to take control over `guile-rs`. It needs moar love, especially as its Scheme.

Please do email me directly if you wish to discuss further: `shymega AT shymega DOT org DOT uk`

Cheers!

**Comment by shymega** [comment]
All.

@lidavidm and I have been discussing this issue over email. The long and short of it is that I am now the maintainer of `guile-rs`, and the repository has been moved to my account. I am _also_ the owner of the [crate][crate] as well.

I'm going to be working on the library in the coming weeks, and making it suitable for production use. I am also juggling other projects / the program we call "Life" as well, so feel free to poke me if it goes a bit silent. I want this project to succeed though.

A big thanks to @lidavidm for giving the maintainer role to me, and for entrusting me with his project.

@christopherdumas I'd like to involve you in the new rebirth of `guile-rs`, we can discuss over email, if you want? Use my email above :)

Thanks all!!

[crate]: https://crates.io/crates/guile

**Comment by christopherdumas** [comment]
Hi @shymega, I sent an email to your email address, but didn't get a response. I've waited a couple days because I know we get busy, but could you let me know if you received it (do I have the right email, etc.)? The gist of it is that while I can't take much part in the design or anything like that, I'd be happy to close out specific issues, such as "no implementation for X part of the FFI" and such. I'd also be able to work on documentation.

**Comment by shymega** [comment]
@christopherdumas Crap, I meant to reply to that. I did get the email, but I've had a bit of an email server blip, and some emails have been overwritten :disappointed: - so I need to check the emails and make sure they're in place. I'll get that done in the next few days, so if I need you to resend it, that I will do.

Sorry for the delay in replying, and my mail server apologizes profusely..

**Comment by christopherdumas** [comment]
Naw its totally fine! I'm going to have a full 8hr workday for two weeks for the first time (my first full-ish time job :), so I may not be on point with emails either.
